function dFds_sym = dFds(t,in2,u1)
%DFDS
%    DFDS_SYM = DFDS(T,IN2,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-May-2021 12:29:53

dFds_sym = reshape([-1.6e+1,1.6e+1,1.2e+1,-9.0],[2,2]);
