function F_sym = dynamics(t,in2,u)
%DYNAMICS
%    F_SYM = DYNAMICS(T,IN2,U)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-May-2021 12:03:01

s1 = in2(1,:);
s2 = in2(2,:);
t2 = cos(t);
t3 = sin(t);
t4 = s1.*1.6e+1;
F_sym = [s2.*1.2e+1+t2.*1.6e+1-t3.*1.3e+1-t4+u;s2.*-9.0-t2.*1.1e+1+t3.*9.0+t4+u];
